"""adding ma tables

Revision ID: 3e60c04c7229
Revises: 
Create Date: 2022-04-28 19:21:58.771692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e60c04c7229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presets', 'volume',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    op.alter_column('presets', 'octave',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    op.alter_column('presets', 'attack',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    op.alter_column('presets', 'decay',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Float(precision=10),
               existing_nullable=False)
    op.alter_column('presets', 'release',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    op.alter_column('presets', 'waveforms',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('presets', 'waveforms',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('presets', 'release',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('presets', 'decay',
               existing_type=sa.Float(precision=10),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=False)
    op.alter_column('presets', 'attack',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('presets', 'octave',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('presets', 'volume',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
