"""Create Presets

Revision ID: 6f929360b67f
Revises: bb7f67d5a04f
Create Date: 2022-04-26 12:39:56.841631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f929360b67f'
down_revision = 'bb7f67d5a04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Numeric(precision=5), nullable=False),
    sa.Column('octave', sa.Float(precision=5), nullable=False),
    sa.Column('attack', sa.Float(precision=5), nullable=False),
    sa.Column('decay', sa.Float(precision=5), nullable=False),
    sa.Column('sustain', sa.Numeric(precision=10), nullable=False),
    sa.Column('release', sa.Float(precision=5), nullable=False),
    sa.Column('waveforms', sa.Float(precision=5), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presets')
    # ### end Alembic commands ###
