"""adding user_id

Revision ID: 89dbaf1e506b
Revises: 6f929360b67f
Create Date: 2022-04-26 12:46:10.498311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dbaf1e506b'
down_revision = '6f929360b67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'presets', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presets', type_='foreignkey')
    op.drop_column('presets', 'user_id')
    # ### end Alembic commands ###
