"""empty message

Revision ID: 9ce7073a4cc2
Revises: 
Create Date: 2023-01-02 16:57:22.369407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce7073a4cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(precision=5), nullable=False),
    sa.Column('octave', sa.Float(precision=5), nullable=False),
    sa.Column('attack', sa.Float(precision=5), nullable=False),
    sa.Column('decay', sa.Float(precision=10), nullable=False),
    sa.Column('sustain', sa.Numeric(precision=10), nullable=False),
    sa.Column('release', sa.Float(precision=5), nullable=False),
    sa.Column('waveforms', sa.Float(precision=5), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('preset_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presets')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
